---
- name: PostgreSQL High Availability Cluster Kurulumu
  hosts: pgsqlsrv
  vars_files:
    - vars/main.yml
  become: true
  become_user: root
  gather_facts: true
  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - import_tasks: tasks/main.yml