---
- name: Operating System Update
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Genel paketlerinin kurulumu
  ansible.builtin.package:
    name: "{{ common_package }}"
    state: present
  notify:
    - enable vmtoolsd

- name: Cluster paketlerinin kurulumu
  ansible.builtin.package:
    name: "{{ cluster_packages }}"
    state: present