---
- name: Storage Edit
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?Storage='
    line: 'Storage=persistent'
    state: present
    backup: true
  notify:
    - restart systemd-journald

- name: Configure systemd default limits
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    state: present
    backup: true
  loop:
    - { key: 'DefaultLimitNOFILE', value: '524288' }
    - { key: 'DefaultLimitNPROC', value: '524288' }
  notify: systemd daemon reload

- name: Deploy chrony.conf
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart chronyd

- name: Configure SMTP relay
  community.general.postconf:
    name: relayhost
    value: "{{ relay_host }}"
  notify:
    - restart postfix

- name: Update /etc/hosts from inventory
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for h in groups['all'] %}
      {{ hostvars[h].ansible_host }} {{ h }}.{{ domain }} {{ h }} {{ h }}-priv
      {% endfor %}

- name: Configure critical kernel parameters for PostgreSQL performance
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-postgresql.conf
  loop:
    - { name: 'vm.swappiness', value: '1' }
    - { name: 'vm.dirty_expire_centisecs', value: '500' }
    - { name: 'vm.dirty_writeback_centisecs', value: '250' }
    - { name: 'vm.dirty_ratio', value: '10' }
    - { name: 'vm.dirty_background_ratio', value: '3' }
    - { name: 'vm.overcommit_memory', value: '2' }
    - { name: 'vm.overcommit_ratio', value: '95' }
    - { name: 'net.core.somaxconn', value: '1024' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '4096' }
    - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
    - { name: 'net.ipv4.tcp_fin_timeout', value: '15' }
    - { name: 'kernel.shmmax', value: '17179869184' } 
    - { name: 'kernel.shmall', value: '4194304' }

    
## Performance Config
#- name: Toplam RAM'in %90'ını G cinsinden hesapla
#  set_fact:
#    memorylimit: "{{ (((ansible_facts.memtotal_mb | int) * 0.90) / 1024) | round(method='ceil') | int }}G"
#
#- name: Pacemaker / Corosync ve user.slice CPU/Mem limitleri
#  ansible.builtin.command: "{{ item }}"
#  loop:
## Pacemaker servis CPU & Memory
#    - "systemctl set-property pacemaker.service CPUAccounting=yes"
#    - "systemctl set-property pacemaker.service CPUQuota=1000%"
#    - "systemctl set-property pacemaker.service MemoryAccounting=yes"
#    - "systemctl set-property pacemaker.service MemoryLimit={{ memorylimit }}"
## Corosync servis CPU
#    - "systemctl set-property corosync.service CPUAccounting=yes"
#    - "systemctl set-property corosync.service CPUQuota=100%"
#    # user.slice kalıcı CPU / Memory limitleri
#    - "systemctl set-property user.slice CPUAccounting=yes"
#    - "systemctl set-property user.slice CPUQuota=100%"
#    - "systemctl set-property user.slice MemoryAccounting=yes"
#    - "systemctl set-property user.slice MemoryLimit=1G"
## user.slice runtime CPU / Memory limitleri (reboot sonrası uçacak)
#    - "systemctl --runtime set-property user.slice CPUAccounting=yes"
#    - "systemctl --runtime set-property user.slice CPUQuota=100%"
#    - "systemctl --runtime set-property user.slice MemoryAccounting=yes"
#    - "systemctl --runtime set-property user.slice MemoryLimit=1G"



