---
- name: Storage Edit
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#?Storage='
    line: 'Storage=persistent'
    state: present
    backup: true
  notify:
    - restart systemd-journald

- name: Configure systemd default limits
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    state: present
    backup: true
  loop:
    - { key: 'DefaultLimitNOFILE', value: '524288' }
    - { key: 'DefaultLimitNPROC', value: '524288' }
  notify: systemd daemon reload

- name: Deploy chrony.conf
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart chronyd

- name: Configure SMTP relay
  community.general.postconf:
    name: relayhost
    value: "{{ relay_host }}"
  notify:
    - restart postfix

- name: Update /etc/hosts from inventory
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for h in groups['all'] %}
      {{ hostvars[h].ansible_host }} {{ h }}.{{ domain }} {{ h }} {{ h }}-priv
      {% endfor %}

- name: Configure critical kernel parameters for PostgreSQL performance
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-postgresql.conf
  loop:
    - { name: 'vm.swappiness', value: '1' }
    - { name: 'vm.dirty_expire_centisecs', value: '500' }
    - { name: 'vm.dirty_writeback_centisecs', value: '250' }
    - { name: 'vm.dirty_ratio', value: '10' }
    - { name: 'vm.dirty_background_ratio', value: '3' }
    - { name: 'vm.overcommit_memory', value: '2' }
    - { name: 'vm.overcommit_ratio', value: '95' }
    - { name: 'net.core.somaxconn', value: '1024' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '4096' }
    - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
    - { name: 'net.ipv4.tcp_fin_timeout', value: '15' }
    - { name: 'kernel.shmmax', value: '17179869184' } 
    - { name: 'kernel.shmall', value: '4194304' }

- name: Toplam RAM'in %90'ını G cinsinden hesapla
  set_fact:
    pacemaker_memorylimit: "{{ (((ansible_facts.memtotal_mb | int) * 0.90) / 1024) | round(method='ceil') | int }}G"

- name: Pacemaker CGroup kaynak limitlerini yapılandır (CPUQuota, MemoryLimit)
  ini_file:
    path: /etc/systemd/system/pacemaker.service.d/resource.conf
    section: Service
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: yes
  loop:
    - { option: 'CPUAccounting', value: 'yes' }
    - { option: 'MemoryAccounting', value: 'yes' }
    - { option: 'CPUQuota', value: '1000%' }
    - { option: 'MemoryLimit', value: "{{ pacemaker_memorylimit }}" }
    - { option: 'LimitNOFILE', value: '65535' }
    - { option: 'LimitNPROC', value: '65535' }
  notify:
    - systemd daemon reload
    - restart pacemaker

- name: Corosync CGroup kaynak limitlerini yapılandır (CPUQuota)
  ini_file:
    path: /etc/systemd/system/corosync.service.d/resource.conf
    section: Service
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: yes
  loop:
    - { option: 'CPUAccounting', value: 'yes' }
    - { option: 'CPUQuota', value: '100%' }
    - { option: 'LimitNOFILE', value: '65535' }
    - { option: 'LimitNPROC', value: '65535' }
  notify:
    - systemd daemon reload
    - restart corosync-qdevice

- name: user.slice CGroup kaynak limitlerini yapılandır (Kalıcı)
  ini_file:
    path: /etc/systemd/system/user.slice.d/resource.conf
    section: Slice # Slice dosyalarında [Slice] bölümü kullanılır
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: yes
  loop:
    - { option: 'CPUAccounting', value: 'yes' }
    - { option: 'MemoryAccounting', value: 'yes' }
    - { option: 'CPUQuota', value: '100%' }
    - { option: 'MemoryLimit', value: '1G' }
  notify:
    - systemd daemon reload
